site_name: Arquitectura Corporativa SD-WAN
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
nav:
  - 🏠 Portada: index.md
  - 🔄 2. OSPF y BGP: 2-enrutamiento-ospf-bgp.md
  - 🛡️ 3. Seguridad FortiGate: 3-seguridad-fortigate.md
  - 📋 Anexo A (Subnetting): 4-anexo-subnetting-vlans.md
  - 🛣️ Anexo B (Rutas): 5-anexo-tablas-enrutamiento.md
